---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars-master.yml
  roles:
    - geerlingguy.jenkins
    - geerlingguy.docker
    - geerlingguy.nginx
  post_tasks:
    - name: Overwrite Jenkins Home ENV var
      lineinfile:
        dest: "{{ jenkins_init_file }}"
        regexp: '^JENKINS_HOME=.*'
        line: 'JENKINS_HOME=/var/jenkins_home'
    - name: Add python script for updating polling config
      copy:
        src: resetNodeToDefault.py
        dest: /var/lib/jenkins/resetNodeToDefault.py
        owner: jenkins
        group: jenkins
        mode: 0500
    - name: For copying files from version control to mounted volume in Jenkins Master
      copy:
        src: users/
        dest: /var/lib/jenkins/users/
        owner: jenkins
        group: jenkins
        mode: 0500