---
 - src: geerlingguy.jenkins
   version: 3.8.0
 - src: geerlingguy.docker
   version: 2.5.3
 - src: geerlingguy.nginx
   version: 2.7.0
 - src: geerlingguy.certbot
   version: 3.0.3
 - src: migibert.terraform
   version: 1.4.0
 - src: geerlingguy.packer
   version: 1.0.2
